# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47b976cdb4ba9eea3bad87ecdb2516dbf0f0ed8245fbb1ccad0b9dd396d38f0bdf0e021754bf0b6609e13d3eb221ebba77dc24978f7f938dd9413729e4005062

test:
  secret_key_base: 01c80274e26c10612d6f047e71707209380a7dfa47c63ac623e396921a81f6f4df24b43d7ec613db21fc380bef5aab1ffb33c3f962fee917ea6ba8ef7e969385

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
